config/routes.rb
Rails.application.routes.draw do
  root "/players#index"
  get "players"=>"players#index"
  get "players/new"=>"players#new"
  post "players" =>"players#create",as:"player_create"
  get "players/:id" => "players#show",as: "player"
  get "players/:id/edit"=>"players#edit",as: "player_edit"
  patch "players/:id"=>"players#update"
  delete "players/:id"=>"players#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  validates :first_name,:last_name,:presence=>true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @player=Player.all
  end
  def new
    @player=Player.new
  end

  def create
    player =Player.new(player_params)
    if player.save
      redirect_to :root
    else
      flash[:errors]=player.errors.full_messages
      redirect_back(fallback_location: player_create_path)
    end
  end
  def show
    @player=Player.find(params[:id])
  end
  def edit

  @player=Player.find(params[:id])
  end
  def update
    player=Player.find(params[:id])
    if player.update(player_params)
      redirect_to :root
    else
      flash[:errors]=player.errors.full_messages
      redirect_back(fallback_location: player_path(player.id))

    end
  end
  def destroy
    player=Player.find(params[:id])
    player.destroy
    redirect_to :root
  end
  private
  def player_params
      params.require(:player).permit(:first_name,:last_name)
  end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <p><%= e %></p>
  <%end %>
<% end%>
<%= form_for(@player) do |p| %>
  <p>
    <%= p.label :first_name %>
    <%= p.text_field :first_name %>
  </p>
  <p>
    <%= p.label :last_name %>
    <%= p.text_field :last_name %>
  </p>
  <%= p.submit %>
<% end %>

app/views/players/edit.html.erb
<%= content_for(:title,"Edit #{@player.first_name} Profile") %>
<h1>Edit <%=@player.first_name %>'s Information</h1>
<%#if flash[:errors] %>
  <%# flash[:errors].each do |e| %>
<!--    <p><%#= e %></p>-->
  <%#end %>
<%# end%>
<!--<form action="\players\<%#= @player.id %>" method="post">-->
<!--  <input type="hidden" name="_method" value="patch">-->
<!--  <input type="hidden" name="authenticity_token" value="<%#= form_authenticity_token %>">-->
<!--  <p>-->
<!--    <label><b>First Name</b></label>-->
<!--    <input type="text" name="player[first_name]" value="<%#=@player.first_name %>">-->

<!--  </p>-->
<!--  <p>-->
<!--    <label><b>Last Name</b></label>-->
<!--    <input type="text" name="player[last_name]" value="<%#=@player.last_name %>">-->

<!--  </p>-->
<!--  <input type="submit" value="update">-->
<!--</form>-->
<%#= form_for(@player) do |p| %>
<!--  <p>-->
    <%#= p.label :first_name %>
    <%#= p.text_field :first_name %>
<!--  </p>-->
<!--  <p>-->
    <%#= p.label :last_name %>
    <%#= p.text_field :last_name %>
<!--  </p>-->
  <%#= p.submit %>
<%# end %>
<%= render partial: "players/form"%>
<%=link_to "Go back",players_path %>

app/views/players/index.html.erb
<%= content_for(:title,"Players") %>
<h1>Listing <%=pluralize(@player.count,"player") %></h1>
<table>
  <thead>
  <tr>
    <td>First name</td>
    <td>Last name</td>
    <td>Information</td>
  </tr>
  </thead>
  <tbody>
  <% @player.each do |player| %>
  <tr>

    <td><%=player.first_name%></td>
    <td><%=player.last_name%></td>
    <td>
      <%= link_to "Show Profile",player_path(player.id)%>
          <%= link_to "Edit Profile",player_edit_path(player.id) %>
      <%= link_to "Delete Profile",player_path(player.id), data:{method: :delete,confirm: "are u sure?"} %>

    </td>


  </tr>
  <% end %>


  </tbody>

</table>
<!--<a href="/players/new">Add New Player</a>-->

<%= link_to "New player",players_new_path%>

app/views/players/new.html.erb
<%= content_for(:title,"Create Player") %>
<h1>Create a New Player</h1>

<%= render partial: "players/form"%>
<%#= form_for(@player) do |p| %>
<!--  <p>-->
    <%#= p.label :first_name %>
    <%#= p.text_field :first_name %>
<!--  </p>-->
<!--  <p>-->
    <%#= p.label :last_name %>
    <%#= p.text_field :last_name %>
<!--  </p>-->
  <%#= p.submit %>
  <%# end %>
<!--<form action="\players" method="post">-->
<!--<input type="hidden" name="authenticity_token" value="<%#= form_authenticity_token %>">-->
<!--  <p>-->
<!--    <label><b>First Name</b></label>-->
<!--    <input type="text" name="player[first_name]">-->

<!--  </p>-->
<!--  <p>-->
<!--    <label><b>Last Name</b></label>-->
<!--    <input type="text" name="player[last_name]">-->

<!--  </p>-->
<!--  <input type="submit" value="Create">-->
<!--</form>-->

app/views/players/show.html.erb
<%= content_for(:title,"#{@player.first_name}'s Profile") %>
<h1>THis is the profile page for <%=@player.first_name %></h1>
<table>
  <thead>
  <tr>
    <td>First name</td>
    <td>Last name</td>

  </tr>
  </thead>
  <tbody>

    <tr>

      <td><%=@player.first_name%></td>
      <td><%=@player.last_name%></td>


    </tr>
  </tbody>
  </table>
<%=link_to "Home Page", root_path %>

app/views/users/index.html.erb
<h1>Login and Registration</h1>